name: Generate WARP WireGuard Config
on:
workflow_dispatch: # Позволяет запускать workflow вручную
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v3
- name: Generate WARP config
id: warp
uses: fscarmen/warp-on-actions@v1.3
with:
mode: wireguard # Указываем, что нужна конфигурация WireGuard
- name: Upload WireGuard config
uses: actions/upload-artifact@v3
with:
name: wireguard-config
path: wgcf-profile.conf
- name: Upload QR code
uses: actions/upload-artifact@v3
with:
name: wireguard-qr
path: wgcf-profile.png
